### ISSUE TITLE
Error when calling add_edges with columns of type object

### ISSUE THREAD

**Issue by AZeed18** [aimclub/BAMT#125]
I have a `BNClassifier` class that inherits from `HybridBN` and `ClassifierMixin`

Its `fit` method includes `add_edges` method from `HybridBN`

I get the following error (with Hill Climbing only):

```
  File "<HIDE>", line 59, in fit
    self.add_edges(df, scoring_function=('BIC',), params={'init_edges': <HIDE>})
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<HIDE>/lib/python3.11/site-packages/bamt/networks/base.py", line 193, in add_edges
    worker.build(
  File "<HIDE>/lib/python3.11/site-packages/bamt/builders/hc_builder.py", line 198, in build
    self.apply_group1(data=data, progress_bar=progress_bar, **self.params)
  File "<HIDE>/lib/python3.11/site-packages/bamt/builders/hc_builder.py", line 121, in apply_group1
    bn = hc_method(
         ^^^^^^^^^^
  File "<HIDE>/lib/python3.11/site-packages/bamt/redef_HC.py", line 165, in hc
    cache[old_cols] = mutual_information(data[:, old_cols])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<HIDE>/lib/python3.11/site-packages/bamt/redef_info_scores.py", line 130, in BIC_local
    log_score = log_lik_local(data, method=method)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<HIDE>/lib/python3.11/site-packages/bamt/redef_info_scores.py", line 123, in log_lik_local
    mutual_information(data, method=method)
  File "<HIDE>/lib/python3.11/site-packages/bamt/mi_entropy_gauss.py", line 224, in mi_gauss
    return mi_gauss(loc_to_DataFrame(data), method, conditional)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "<HIDE>/lib/python3.11/site-packages/bamt/preprocess/numpy_pandas.py", line 16, in loc_to_DataFrame
    nodes_type = get_type_numpy(data)
                 ^^^^^^^^^^^^^^^^^^^^
  File "<HIDE>/lib/python3.11/site-packages/bamt/preprocess/numpy_pandas.py", line 50, in get_type_numpy
    all_row_is_integer = all(
                         ^^^^
  File "<HIDE>/lib/python3.11/site-packages/bamt/preprocess/numpy_pandas.py", line 51, in <genexpr>
    np.issubdtype(x, np.integer) or x.is_integer() for x in row
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<HIDE>/lib/python3.11/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
TypeError: Cannot interpret '39' as a data type
```

`39` is the value of the second column (an `np.dtypes.Int32DType` column) in the first row

Datatypes in my `DataFrame` are:

- `np.dtypes.Float32DType` for continuous data
- `np.dtypes.Int32DType` for discrete numerical data
- `np.dtypes.ObjectDType` for categorical data

I don't get this error when no columns of `np.dtypes.ObjectDType` type exist

**Comment by jrzkaminski** [comment]
Is `39` a column name or a value? @AZeed18

**Comment by AZeed18** [comment]
> Is it possible to try default non-numpy datatypes from python like int or float?

Sorry for late reply

Using `X_train[feature].astype(int)` makes use of NumPy's `int64` instead, it seems that the issue doesn't appear when no features of `np.dtypes.ObjectDType` datatypes are there

**Comment by Roman223** [comment]
Can you provide more details on x object?

I'm not managed to reproduce it with:

```
n [6]: a = pd.Series([39], dtype=np.int32)

In [7]: a
Out[7]: 
0    39
dtype: int32

In [8]: np.issubdtype(a, np.integer)
Out[8]: True

```

**Comment by Roman223** [comment]
But I have a similar error with:
```
In [28]: np.issubdtype("32", np.integer)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[28], line 1
----> 1 np.issubdtype("32", np.integer)

File <HIDE>t/venv/lib/python3.12/site-packages/numpy/core/numerictypes.py:417, in issubdtype(arg1, arg2)
    359 r"""
    360 Returns True if first argument is a typecode lower/equal in type hierarchy.
    361 
   (...)
    414 
    415 """
    416 if not issubclass_(arg1, generic):
--> 417     arg1 = dtype(arg1).type
    418 if not issubclass_(arg2, generic):
    419     arg2 = dtype(arg2).type

TypeError: data type '' not understood

```

**Comment by Roman223** [comment]
Thanks for issue, @AZeed18!

It seems you are trying to use group1 on disc data. Please notice that score functions of group 1 **work without discretization**, but **not without encoding**. 

It's correct behavior you have faced, just use `LabelEncoder`. 

The only problem I see here is the one in error handling. I think we will add error when discrete data is passed into structure learning step.

**Comment by AZeed18** [comment]
Thanks, @Roman223.

I just got few questions:

- What are group 1 score functions?
- What if that variable is nominal and not ordinal, should I still apply `LabelEncoder` (i.e., `OrdinalEncoder`)?
- Does this problem apply only to structure learning and not parameter estimation?

**Comment by Roman223** [comment]
1. Group 1 is technical name for MI, BIC, AIC, LL scoring functions and related modules.
See this snippet from hill climbing structure builder (`bamt/builders/hc_builders.py`. line 195):
```python
        if self.scoring_function[0] == "K2":
            self.apply_K2(data=data, progress_bar=progress_bar, **self.params)
        elif self.scoring_function[0] in ["MI", "LL", "BIC", "AIC"]:
            self.apply_group1(data=data, progress_bar=progress_bar, **self.params)
```
2. Yes. There must be no strings for structure training. Only numbers.
3. Yes, this problem appears only in structure learning. Consider this example from [docs](https://bamt.readthedocs.io/en/latest/examples/learn_save.html):
```python
# add nodes to network
bn.add_nodes(info)

# using mutual information as scoring function for structure learning
bn.add_edges(discretized_data, scoring_function=('MI',))

<...>

bn.fit_parameters(data)
```
Notice that for training parameters an initial dataset is used. This was done because of type of variable. Indeed, you can pass discretized data to parameters learning, but in this case only discrete values will be evaluated (e.g. only values [0, 1, 2] will be obtained on sampling instead of [cat1, cat2, cat3])

**Comment by AZeed18** [comment]
> 2. Yes. There must be no strings for structure training. Only numbers.

Wouldn't that falsely imply order (e.g., 3 is closer to 2 than to 1)?

**Comment by Roman223** [comment]
Why do you think so? It shouldn't...

**Comment by AZeed18** [comment]
> Why do you think so? It shouldn't...

You're right, I think converting a nominal variable to a numerical implies order only in limited to algorithms that consider distance (like KNN and SVM)
